<ramu>:
	rows:25
	id:ram
	su:su
	Label:
		font_size:30
		text: '[b]Garuda.inc[/b]'
		canvas.before:
			Color:
				rgb: 1,0,0
			Rectangle:
				pos:self.pos
				size:self.size 
		markup: True
		size_hint: (1,0.1)
	Button:
		font_size:30
		id:su
		text: '[b]suduko-solver[/b] Press ok to Get the answer for suduko'
		background_color: (0.2,0.8,1,1.7)
		markup: True
		size_hint: (1,0.1)
<error>:
	title:'error'
	size_hint:(.75,.4)
	Label:
		text:'only integers should be written'